
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: todo_app_development
  pool: 5
  username:
  password:

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: todo_app_test
  pool: 5
  username:
  password:

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: todo_app_production
  pool: 5
  username:
  password:
