
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: todo_app_development
  pool: 5

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: todo_app_production
  pool: 5