
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: to_do_list_development
  pool: 5
 
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: to_do_list_test
  pool: 5


